# Gomoku Classical Configuration
# Classical MCTS implementation

experiment_name: gomoku_classical
seed: 42
log_level: INFO
num_iterations: 500

game:
  game_type: gomoku
  board_size: 15
  gomoku_use_renju: false
  gomoku_use_omok: false
  gomoku_use_pro_long_opening: false

mcts:
  # Core MCTS parameters
  num_simulations: 800
  c_puct: 1.0
  dirichlet_alpha: 0.3  # Standard for Gomoku
  dirichlet_epsilon: 0.25  # Standard exploration noise
  temperature: 1.0
  temperature_threshold: 30
  temperature_final: 0.1
  
  # Performance optimization
  min_wave_size: 2048  # Optimized for RTX 3060 Ti
  max_wave_size: 3072  # Maximum for hardware
  batch_size: 512  # Optimized batch size
  
  # Virtual loss for exploration diversity
  virtual_loss: 3.0
  enable_virtual_loss: true
  
  # Memory settings - 8GB VRAM + 64GB RAM
  memory_pool_size_mb: 4096
  max_tree_nodes: 1000000
  tree_reuse: true
  
  # GPU optimization
  use_cuda_graphs: true
  use_mixed_precision: true
  use_tensor_cores: true
  
  # Classical MCTS only
  enable_quantum: false
  
  # Progressive widening parameters for lazy expansion
  enable_progressive_widening: true
  progressive_widening_alpha: 0.5  # k = alpha * sqrt(n) - controls expansion rate
  progressive_widening_base: 10.0  # Minimum children to expand at each node
  
  # RAVE (Rapid Action Value Estimation) for faster learning
  enable_rave: true
  rave_c: 3000.0  # RAVE exploration constant
  rave_threshold: 50  # Disable RAVE after this many training iterations
  
  # Tactical boost for finding important moves with untrained networks
  enable_tactical_boost: true
  tactical_boost_strength: 0.3      # 0.0 = no boost, 1.0 = full replacement
  tactical_boost_decay: 0.99        # Decay factor per iteration
  
  # Gomoku tactical parameters
  gomoku_win_boost: 100.0           # Immediate win move
  gomoku_block_win_boost: 90.0      # Block opponent win
  gomoku_open_four_boost: 50.0      # Create open four
  gomoku_block_four_boost: 45.0     # Block opponent open four
  gomoku_threat_base_boost: 40.0    # Base for multiple threats
  gomoku_threat_multiplier: 5.0     # Per additional threat
  gomoku_three_boost: 20.0          # Create three in a row
  gomoku_block_three_boost: 18.0    # Block opponent three
  gomoku_center_boost: 3.0          # Central position bonus
  gomoku_connection_boost: 2.0      # Per connection bonus
  
  # Device - Ryzen 9 5900X
  # CSR tree configuration
  csr_max_actions: 225  # 15x15 board positions

  device: cuda
  num_threads: 24
  
  # TensorRT acceleration (enabled by default for RTX GPUs)
  use_tensorrt: true
  tensorrt_fp16: true
  tensorrt_fallback: true
  tensorrt_workspace_size: 2048  # MB - workspace size for optimization
  tensorrt_int8: false           # INT8 quantization (requires calibration)
  tensorrt_max_batch_size: 512   # Maximum batch size to optimize for
  tensorrt_engine_cache_dir: null # Custom cache directory

network:
  # Standard network configuration
  model_type: resnet
  input_channels: 19
  input_representation: basic
  num_res_blocks: 12
  num_filters: 192
  value_head_hidden_size: 256
  policy_head_filters: 2
  
  # Regularization
  dropout_rate: 0.1
  batch_norm: true
  batch_norm_momentum: 0.997
  l2_regularization: 0.0001
  
  # Activation
  activation: relu
  weight_init: he_normal

training:
  # Basic training parameters
  batch_size: 768  # Optimized for RTX 3060 Ti
  learning_rate: 0.01
  learning_rate_schedule: cosine
  lr_decay_steps: 100
  lr_decay_rate: 0.1
  min_learning_rate: 0.00001
  
  # Optimizer
  optimizer: adam
  adam_beta1: 0.9
  adam_beta2: 0.999
  weight_decay: 0.0001
  
  # Gradient handling
  gradient_accumulation_steps: 1
  max_grad_norm: 5.0
  
  # Training loop
  num_epochs: 10
  
  # Self-play - 12 cores
  num_games_per_iteration: 100
  num_workers: 1
  max_moves_per_game: 225
  resign_threshold: -0.95
  
  # Data handling - 64GB RAM
  window_size: 500000  # Standard buffer size
  augment_data: true
  mixed_precision: true
  
  # Paths
  save_dir: checkpoints
  tensorboard_dir: runs
  data_dir: self_play_data

arena:
  # Evaluation settings - 12 cores
  num_games: 180  # More games for statistical significance
  num_workers: 12
  # games_per_worker: auto-calculated based on num_games / num_workers
  win_threshold: 0.55
  statistical_significance: true
  confidence_level: 0.95
  
  # Game settings - classical for fair evaluation
  temperature: 0.1
  mcts_simulations: 400
  c_puct: 1.0
  max_moves: 225
  
  # ELO tracking
  elo_k_factor: 32.0
  elo_initial_rating: 0.0  # Standard ELO starting rating
  elo_anchor_rating: 0.0
  update_elo: true
  
  # Random policy checks
  # min_win_rate_vs_random: 0.95  # DEPRECATED - Now using dynamic logarithmic scheduling
  # Dynamic threshold: starts at 5%, reaches 100% at iteration 150
  
  # Logging
  save_game_records: false
  save_arena_logs: true
  arena_log_dir: arena_logs
  elo_save_path: elo_ratings.json