# Gomoku One-Loop Quantum Configuration
# Full quantum field theory corrections for maximum exploration

experiment_name: gomoku_one_loop_quantum
seed: 42
log_level: INFO
num_iterations: 500

game:
  game_type: gomoku
  board_size: 15
  gomoku_use_renju: false
  gomoku_use_omok: false
  gomoku_use_pro_long_opening: false

mcts:
  # Core MCTS parameters
  num_simulations: 800
  c_puct: 1.0
  dirichlet_alpha: 0.0
  dirichlet_epsilon: 0.0
  temperature: 1.0
  temperature_threshold: 30
  temperature_final: 0.1
  
  # Performance optimization - adjusted for one-loop overhead
  min_wave_size: 1536  # Lower for one-loop overhead
  max_wave_size: 2560  # Slightly reduced
  batch_size: 320  # Balanced for quantum overhead
  
  # Virtual loss - disabled for quantum versions (quantum interference handles diversity)
  virtual_loss: 0.0
  enable_virtual_loss: false
  
  # Memory settings - 8GB VRAM + 64GB RAM
  memory_pool_size_mb: 4096
  max_tree_nodes: 1000000
  tree_reuse: true
  
  # GPU optimization
  use_cuda_graphs: true
  use_mixed_precision: true
  use_tensor_cores: true
  
  # One-loop quantum features
  quantum_level: one_loop
  enable_quantum: true
  quantum_version: 'v2'
  quantum_config:
    quantum_coupling: 0.15  # Stronger coupling for one-loop
    quantum_temperature: 1.5
    decoherence_rate: 0.01
    measurement_noise: 0.001
    # Path integral configuration
    path_integral_steps: 20
    path_integral_beta: 1.0
    use_wick_rotation: true
    # Interference settings
    interference_alpha: 0.08
    interference_method: minhash
    minhash_size: 128  # Larger for one-loop
    phase_kick_strength: 0.15
  
  # Progressive widening parameters for lazy expansion
  progressive_widening_alpha: 0.5  # k = alpha * sqrt(n) - controls expansion rate
  progressive_widening_base: 10.0  # Minimum children to expand at each node
  
  # Device - Ryzen 9 5900X
  device: cuda
  num_threads: 24
  
  # TensorRT acceleration (enabled by default for RTX GPUs)
  use_tensorrt: true
  tensorrt_fp16: true
  tensorrt_fallback: true
  tensorrt_workspace_size: 2048  # MB - workspace size for optimization
  tensorrt_int8: false           # INT8 quantization (requires calibration)
  tensorrt_max_batch_size: 512   # Maximum batch size to optimize for
  tensorrt_engine_cache_dir: null # Custom cache directory

network:
  # Slightly larger network for quantum features
  model_type: resnet
  input_channels: 20
  num_res_blocks: 12
  num_filters: 192
  value_head_hidden_size: 256
  policy_head_filters: 2
  
  # Regularization
  dropout_rate: 0.1
  batch_norm: true
  batch_norm_momentum: 0.997
  l2_regularization: 0.0001
  
  # Activation
  activation: relu
  weight_init: he_normal

training:
  # Basic training parameters
  batch_size: 640  # Slightly lower due to quantum overhead
  learning_rate: 0.01
  learning_rate_schedule: cosine  # Smoother for quantum
  lr_decay_steps: 100
  lr_decay_rate: 0.1
  min_learning_rate: 0.00001
  
  # Optimizer
  optimizer: adam
  adam_beta1: 0.9
  adam_beta2: 0.999
  weight_decay: 0.0001
  
  # Gradient handling
  gradient_accumulation_steps: 1
  max_grad_norm: 5.0
  
  # Training loop
  num_epochs: 10
  
  # Self-play with full quantum - 12 cores
  num_games_per_iteration: 100
  num_workers: 1
  max_moves_per_game: 225
  resign_threshold: -0.95
  
  # Data handling - 64GB RAM
  window_size: 600000  # Larger buffer for quantum diversity
  augment_data: true
  mixed_precision: true
  
  # Paths
  save_dir: checkpoints
  tensorboard_dir: runs
  data_dir: self_play_data

arena:
  # Evaluation settings - 12 cores
  num_games: 180  # More games for statistical significance
  num_workers: 12
  # games_per_worker: auto-calculated based on num_games / num_workers
  win_threshold: 0.55
  statistical_significance: true
  confidence_level: 0.95
  
  # Game settings - classical for fair evaluation
  temperature: 0.1
  mcts_simulations: 400
  c_puct: 1.0
  max_moves: 225
  
  # ELO tracking
  elo_k_factor: 32.0
  elo_initial_rating: 0.0  # Standard ELO starting rating
  elo_anchor_rating: 0.0
  update_elo: true
  
  # Random policy checks
  min_win_rate_vs_random: 0.95
  
  # Logging
  save_game_records: false
  save_arena_logs: true
  arena_log_dir: arena_logs
  elo_save_path: elo_ratings.json