# Minimal Test Configuration
# For quick testing and debugging - not for actual training

experiment_name: test_run
seed: 42
log_level: DEBUG
num_iterations: 5

game:
  game_type: gomoku
  board_size: 9  # Smaller board for testing

mcts:
  # Minimal settings for speed
  num_simulations: 100
  c_puct: 1.0
  dirichlet_alpha: 0.3
  dirichlet_epsilon: 0.25
  
  # Small batches for testing
  min_wave_size: 64
  max_wave_size: 128
  batch_size: 64
  
  # Virtual loss disabled for testing
  enable_virtual_loss: false
  virtual_loss: 0.0
  
  # Minimal memory
  memory_pool_size_mb: 512
  max_tree_nodes: 10000
  enable_subtree_reuse: false
  
  # Performance settings
  enable_fast_ucb: true
  
  # Tactical boost for finding important moves
  enable_tactical_boost: true
  tactical_boost_strength: 0.3
  tactical_boost_decay: 0.99
  
  # CSR tree configuration for 9x9 test board
  csr_max_actions: 225  # Using default even for smaller board
  
  # Device - still use all threads for testing
  device: cuda
  # Mixed precision handled by training section
  num_threads: 12
  
  # TensorRT settings moved to training section

network:
  # Tiny network for testing
  model_type: resnet
  input_channels: 18
  input_representation: basic
  num_res_blocks: 2
  num_filters: 32
  value_head_hidden_size: 64

training:
  # Minimal training
  batch_size: 64
  learning_rate: 0.01
  num_epochs: 2
  
  # Few self-play games for testing
  num_games_per_iteration: 12
  max_moves_per_game: 81
  
  # Small buffer
  window_size: 1000
  augment_data: false
  mixed_precision: false
  dataloader_workers: 2
  pin_memory: true

arena:
  # Quick evaluation
  num_games: 12
  
  # ELO tracking
  update_elo: true
  elo_k_factor: 32.0
  elo_initial_rating: 0.0
  win_threshold: 0.5
  
  # Fast games
  temperature: 0.1
  mcts_simulations: 50
  
  # Random player evaluation uses dynamic thresholds
  
  # Minimal logging
  save_game_records: false
  save_arena_logs: false