# Test configuration for illegal moves with subtree reuse disabled
experiment_name: test_illegal_moves
seed: 42
log_level: INFO
num_iterations: 1

game:
  game_type: gomoku
  board_size: 15

mcts:
  backend: hybrid
  num_simulations: 100
  c_puct: 1.0
  temperature: 1.0
  enable_subtree_reuse: false  # Critical: test with subtree reuse disabled
  device: cuda
  
self_play:
  num_games_per_iteration: 5
  num_parallel_games: 2
  device: cuda
  
training:
  enabled: false  # Skip training for this test
  
model:
  architecture: alphazero_resnet
  num_blocks: 10
  num_filters: 128
  
evaluator:
  type: mock  # Use mock evaluator for speed