game:
  game_type: gomoku
  board_size: 15
  go_komi: 7.5
  go_rules: chinese
  go_superko: true
  gomoku_use_renju: false
  gomoku_use_omok: false
  gomoku_use_pro_long_opening: false
  chess_960: false
  chess_starting_fen: null
mcts:
  num_simulations: 800
  c_puct: 1.0
  dirichlet_alpha: 0.15
  dirichlet_epsilon: 0.25
  temperature: 1.0
  temperature_threshold: 30
  temperature_final: 0.1
  min_wave_size: 256
  max_wave_size: 3072
  adaptive_wave_sizing: false
  batch_size: 128
  virtual_loss: 3.0
  memory_pool_size_mb: 1024
  max_tree_nodes: 200000
  tree_reuse: true
  tree_reuse_fraction: 0.5
  use_cuda_graphs: true
  use_mixed_precision: true
  use_tensor_cores: true
  compile_mode: reduce-overhead
  quantum_level: classical
  enable_quantum: false
  quantum_coupling: 0.1
  quantum_temperature: 1.0
  decoherence_rate: 0.01
  measurement_noise: 0.0
  path_integral_steps: 10
  path_integral_beta: 1.0
  use_wick_rotation: true
  interference_alpha: 0.05
  interference_method: minhash
  minhash_size: 64
  phase_kick_strength: 0.1
  wave_min_size: 512
  wave_max_size: 1024
  wave_adaptive_sizing: false
  wave_target_sims_per_second: 100000
  wave_target_gpu_utilization: 0.95
  wave_num_pipelines: 3
  wave_async_expansion: true
  wave_prefetch_evaluations: true
  wave_memory_pool_mb: 1024
  csr_max_actions: 10
  csr_use_sparse_operations: true
  interference_threshold: 0.1
  constructive_interference_factor: 0.1
  destructive_interference_factor: 0.05
  device: cuda
  num_threads: 4
network:
  model_type: resnet
  input_channels: 20
  num_res_blocks: 10
  num_filters: 128
  value_head_hidden_size: 256
  policy_head_filters: 2
  dropout_rate: 0.1
  batch_norm: true
  batch_norm_momentum: 0.997
  l2_regularization: 0.0001
  activation: relu
  leaky_relu_alpha: 0.01
  weight_init: he_normal
  bias_init: 0.0
training:
  batch_size: 256
  learning_rate: 0.01
  learning_rate_schedule: step
  lr_decay_steps: 50
  lr_decay_rate: 0.1
  min_learning_rate: 1.0e-05
  optimizer: adam
  adam_beta1: 0.9
  adam_beta2: 0.999
  adam_epsilon: 1.0e-08
  sgd_momentum: 0.9
  sgd_nesterov: true
  weight_decay: 0.0001
  gradient_accumulation_steps: 4
  max_grad_norm: 5.0
  gradient_clip_value: null
  final_tournament_enabled: true
  final_tournament_model_selection_step: 10
  final_tournament_max_models: 10
  num_epochs: 10
  checkpoint_interval: 50
  validation_interval: 10
  early_stopping_patience: 50
  early_stopping_min_delta: 0.0001
  num_games_per_iteration: 100
  num_workers: 4
  games_per_worker: 25
  max_moves_per_game: 225
  resign_threshold: -0.95
  resign_check_moves: 10
  window_size: 200000
  sample_weight_by_game_length: true
  augment_data: true
  shuffle_buffer_size: 10000
  dataloader_workers: 4
  pin_memory: true
  mixed_precision: true
  amp_opt_level: O1
  loss_scale: dynamic
  static_loss_scale: 1.0
  eval_temperature: 0.1
  eval_num_games: 20
  save_dir: checkpoints
  tensorboard_dir: runs
  data_dir: self_play_data
arena:
  num_games: 40
  num_workers: 2
  games_per_worker: 20
  win_threshold: 0.55
  statistical_significance: true
  confidence_level: 0.95
  temperature: 0.1
  mcts_simulations: 400
  c_puct: 1.0
  max_moves: 225
  time_limit_seconds: null
  randomize_start_player: true
  elo_k_factor: 32.0
  elo_initial_rating: 1500.0
  elo_anchor_rating: 0.0
  update_elo: true
  eval_vs_random_interval: 10
  eval_vs_random_games: 20
  min_win_rate_vs_random: 0.95
  tournament_rounds: 1
  tournament_games_per_pair: 10
  save_game_records: false
  save_arena_logs: true
  arena_log_dir: arena_logs
  elo_save_path: elo_ratings.json
experiment_name: gomoku_classical_optimized
seed: 42
log_level: INFO
num_iterations: 300
