# Thermodynamic Configuration for Quantum MCTS
# This replaces hard-coded constants with configurable parameters

# Physical Constants
boltzmann_constant: 1.0  # Set to 1 for natural units
minimum_temperature: 0.1  # Minimum temperature to avoid singularities
minimum_probability: 1.0e-12  # Minimum probability to avoid log(0)

# Energy Definitions
energy:
  type: "policy_log_prob"  # Use E = -log(P_policy)
  regularization: 1.0e-12  # Small constant to avoid log(0)
  
# Temperature Definitions  
temperature:
  type: "policy_entropy"  # Derive from policy entropy
  base_temperature: 0.5  # Base temperature offset
  entropy_scaling: 1.0   # Scale factor for policy entropy
  min_temp: 0.1          # Minimum temperature
  max_temp: 10.0         # Maximum temperature
  n_points: 20           # Number of temperature points

# Internal Energy (Canonical Ensemble)
internal_energy:
  type: "canonical_average"  # U = ⟨E⟩_β
  ensemble: "canonical"      # Canonical ensemble
  
# Heat Capacity
heat_capacity:
  type: "fluctuation_formula"  # C = β² ⟨(ΔE)²⟩
  min_capacity: 0.01          # Minimum heat capacity

# Work Protocol
work:
  type: "parameter_integral"  # W = ∫ θ̇ · ∂_θ E dt
  parameters:
    - "beta"      # Inverse temperature
    - "c_puct"    # MCTS exploration parameter
  scaling_factor: 1.0
  
# Free Energy
free_energy:
  type: "partition_function"  # F = -(1/β) log Z
  importance_sampling: true   # Use importance sampling for Z
  min_partition: 1.0e-12     # Minimum partition function

# Entropy Production
entropy_production:
  type: "flux_force_pairs"  # σ = Σ J_i X_i
  fluxes:
    - "visit_flow"          # Flow between tree nodes
    - "policy_change"       # Policy evolution
  forces:
    - "energy_gradient"     # ∇E
    - "temperature_gradient" # ∇T
  scaling_factor: 1.0       # Adaptive scaling is used automatically (legacy 0.001 removed)
  min_production: 0.0       # Ensure σ ≥ 0 (Second Law)

# Jarzynski Equality
jarzynski:
  tolerance: 0.1            # 10% tolerance for equality check
  min_trajectories: 100     # Minimum work trajectories
  bootstrap_samples: 1000   # Bootstrap samples for error estimation

# Visualization Parameters
visualization:
  max_data_points: 1000     # Maximum points for large dataset plots
  temperature_range: [0.1, 5.0]  # Temperature range for plots
  energy_bins: 50           # Number of bins for energy histograms
  work_bins: 30            # Number of bins for work distributions
  
# Numerical Stability
numerical:
  overflow_threshold: 700.0    # exp(x) overflow threshold
  underflow_threshold: -700.0  # exp(x) underflow threshold
  convergence_tolerance: 1.0e-6  # Convergence tolerance
  max_iterations: 1000         # Maximum iterations for iterative methods

# Validation
validation:
  check_second_law: true      # Verify σ ≥ 0
  check_jarzynski: true       # Verify Jarzynski equality
  check_maxwell_relations: false  # Skip Maxwell relations (not applicable)
  error_on_violation: false  # Warning instead of error on violations